server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: 1234
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
            allowedOrigins:
              - "http://localhost:3000"
            allowedHeaders: "*"
      routes:
        - id: qna-service
          uri: lb://QNA-SERVICE
          predicates:
            - Path= /qna/**

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httpstrace, busrefresh
